//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let chat = _ModuleRegistry.module("chat");

    chat.MessageType = Slice.defineEnum([
        ['TEXT', 0], ['AUDIO', 1]]);

    chat.Message = class
    {
        constructor(id = "", from = "", to = "", scope = "", type = chat.MessageType.TEXT, text = "", audioUrl = "", createdAt = new Ice.Long(0, 0), mimeType = "", duration = 0.0)
        {
            this.id = id;
            this.from = from;
            this.to = to;
            this.scope = scope;
            this.type = type;
            this.text = text;
            this.audioUrl = audioUrl;
            this.createdAt = createdAt;
            this.mimeType = mimeType;
            this.duration = duration;
        }

        _write(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.from);
            ostr.writeString(this.to);
            ostr.writeString(this.scope);
            chat.MessageType._write(ostr, this.type);
            ostr.writeString(this.text);
            ostr.writeString(this.audioUrl);
            ostr.writeLong(this.createdAt);
            ostr.writeString(this.mimeType);
            ostr.writeDouble(this.duration);
        }

        _read(istr)
        {
            this.id = istr.readString();
            this.from = istr.readString();
            this.to = istr.readString();
            this.scope = istr.readString();
            this.type = chat.MessageType._read(istr);
            this.text = istr.readString();
            this.audioUrl = istr.readString();
            this.createdAt = istr.readLong();
            this.mimeType = istr.readString();
            this.duration = istr.readDouble();
        }

        static get minWireSize()
        {
            return  24;
        }
    };

    Slice.defineStruct(chat.Message, false, true);

    Slice.defineSequence(chat, "StringSeqHelper", "Ice.StringHelper", false);

    Slice.defineSequence(chat, "ByteSeqHelper", "Ice.ByteHelper", true);

    Slice.defineSequence(chat, "MessageSeqHelper", "chat.Message", false);

    const iceC_chat_ChatClient_ids = [
        "::Ice::Object",
        "::chat::ChatClient"
    ];

    chat.ChatClient = class extends Ice.Object
    {
    };

    chat.ChatClientPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(chat.ChatClient, chat.ChatClientPrx, iceC_chat_ChatClient_ids, 1,
    {
        "onMessage": [, , , , , [[chat.Message]], , , , ],
        "onAudioChunk": [, , , , , [[7], [3], [3], ["chat.ByteSeqHelper"], [7]], , , , ],
        "onAudioEnd": [, , , , , [[7], [7], [7], [7], [6]], , , , ]
    });

    const iceC_chat_ChatService_ids = [
        "::Ice::Object",
        "::chat::ChatService"
    ];

    chat.ChatService = class extends Ice.Object
    {
    };

    chat.ChatServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(chat.ChatService, chat.ChatServicePrx, iceC_chat_ChatService_ids, 1,
    {
        "registerClient": [, , , , , [[7], ["chat.ChatClientPrx"]], , , , ],
        "unregisterClient": [, , , , , [[7]], , , , ],
        "createGroup": [, , , , [7], [[7], ["chat.StringSeqHelper"]], , , , ],
        "sendText": [, , , , , [[7], [7], [7], [7]], , , , ],
        "getHistory": [, , , , ["chat.MessageSeqHelper"], [[7], [7]], , , , ],
        "beginAudio": [, , , , [7], [[7], [7], [7], [7]], , , , ],
        "sendAudioChunk": [, , , , , [[7], [3], [3], ["chat.ByteSeqHelper"]], , , , ],
        "endAudio": [, , , , , [[7], [6]], , , , ]
    });
    exports.chat = chat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
