//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatService extends com.zeroc.Ice.Object
{
    void registerClient(String userId, ChatClientPrx cb, com.zeroc.Ice.Current current);

    void unregisterClient(String userId, com.zeroc.Ice.Current current);

    String createGroup(String name, String[] members, com.zeroc.Ice.Current current);

    void sendText(String toType, String to, String fromUser, String text, com.zeroc.Ice.Current current);

    Message[] getHistory(String scope, String id, com.zeroc.Ice.Current current);

    String beginAudio(String toType, String to, String fromUser, String mimeType, com.zeroc.Ice.Current current);

    void sendAudioChunk(String streamId, int index, int total, byte[] data, com.zeroc.Ice.Current current);

    void endAudio(String streamId, double duration, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::chat::ChatService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::chat::ChatService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registerClient(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        ChatClientPrx iceP_cb;
        iceP_userId = istr.readString();
        iceP_cb = ChatClientPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.registerClient(iceP_userId, iceP_cb, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_unregisterClient(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        obj.unregisterClient(iceP_userId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_name;
        String[] iceP_members;
        iceP_name = istr.readString();
        iceP_members = istr.readStringSeq();
        inS.endReadParams();
        String ret = obj.createGroup(iceP_name, iceP_members, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendText(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_toType;
        String iceP_to;
        String iceP_fromUser;
        String iceP_text;
        iceP_toType = istr.readString();
        iceP_to = istr.readString();
        iceP_fromUser = istr.readString();
        iceP_text = istr.readString();
        inS.endReadParams();
        obj.sendText(iceP_toType, iceP_to, iceP_fromUser, iceP_text, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getHistory(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_scope;
        String iceP_id;
        iceP_scope = istr.readString();
        iceP_id = istr.readString();
        inS.endReadParams();
        Message[] ret = obj.getHistory(iceP_scope, iceP_id, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageSeqHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_beginAudio(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_toType;
        String iceP_to;
        String iceP_fromUser;
        String iceP_mimeType;
        iceP_toType = istr.readString();
        iceP_to = istr.readString();
        iceP_fromUser = istr.readString();
        iceP_mimeType = istr.readString();
        inS.endReadParams();
        String ret = obj.beginAudio(iceP_toType, iceP_to, iceP_fromUser, iceP_mimeType, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudioChunk(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_streamId;
        int iceP_index;
        int iceP_total;
        byte[] iceP_data;
        iceP_streamId = istr.readString();
        iceP_index = istr.readInt();
        iceP_total = istr.readInt();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendAudioChunk(iceP_streamId, iceP_index, iceP_total, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_endAudio(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_streamId;
        double iceP_duration;
        iceP_streamId = istr.readString();
        iceP_duration = istr.readDouble();
        inS.endReadParams();
        obj.endAudio(iceP_streamId, iceP_duration, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "beginAudio",
        "createGroup",
        "endAudio",
        "getHistory",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "registerClient",
        "sendAudioChunk",
        "sendText",
        "unregisterClient"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_beginAudio(this, in, current);
            }
            case 1:
            {
                return _iceD_createGroup(this, in, current);
            }
            case 2:
            {
                return _iceD_endAudio(this, in, current);
            }
            case 3:
            {
                return _iceD_getHistory(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 8:
            {
                return _iceD_registerClient(this, in, current);
            }
            case 9:
            {
                return _iceD_sendAudioChunk(this, in, current);
            }
            case 10:
            {
                return _iceD_sendText(this, in, current);
            }
            case 11:
            {
                return _iceD_unregisterClient(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
