//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatClientPrx extends com.zeroc.Ice.ObjectPrx
{
    default void onMessage(Message m)
    {
        onMessage(m, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onMessage(Message m, java.util.Map<String, String> context)
    {
        _iceI_onMessageAsync(m, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onMessageAsync(Message m)
    {
        return _iceI_onMessageAsync(m, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onMessageAsync(Message m, java.util.Map<String, String> context)
    {
        return _iceI_onMessageAsync(m, context, false);
    }

    /**
     * @hidden
     * @param iceP_m -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onMessageAsync(Message iceP_m, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Message.ice_write(ostr, iceP_m);
                 }, null);
        return f;
    }

    default void onAudioChunk(String streamId, int index, int total, byte[] data, String mimeType)
    {
        onAudioChunk(streamId, index, total, data, mimeType, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onAudioChunk(String streamId, int index, int total, byte[] data, String mimeType, java.util.Map<String, String> context)
    {
        _iceI_onAudioChunkAsync(streamId, index, total, data, mimeType, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onAudioChunkAsync(String streamId, int index, int total, byte[] data, String mimeType)
    {
        return _iceI_onAudioChunkAsync(streamId, index, total, data, mimeType, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onAudioChunkAsync(String streamId, int index, int total, byte[] data, String mimeType, java.util.Map<String, String> context)
    {
        return _iceI_onAudioChunkAsync(streamId, index, total, data, mimeType, context, false);
    }

    /**
     * @hidden
     * @param iceP_streamId -
     * @param iceP_index -
     * @param iceP_total -
     * @param iceP_data -
     * @param iceP_mimeType -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onAudioChunkAsync(String iceP_streamId, int iceP_index, int iceP_total, byte[] iceP_data, String iceP_mimeType, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onAudioChunk", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_streamId);
                     ostr.writeInt(iceP_index);
                     ostr.writeInt(iceP_total);
                     ostr.writeByteSeq(iceP_data);
                     ostr.writeString(iceP_mimeType);
                 }, null);
        return f;
    }

    default void onAudioEnd(String streamId, String to, String from, String mimeType, double duration)
    {
        onAudioEnd(streamId, to, from, mimeType, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onAudioEnd(String streamId, String to, String from, String mimeType, double duration, java.util.Map<String, String> context)
    {
        _iceI_onAudioEndAsync(streamId, to, from, mimeType, duration, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onAudioEndAsync(String streamId, String to, String from, String mimeType, double duration)
    {
        return _iceI_onAudioEndAsync(streamId, to, from, mimeType, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onAudioEndAsync(String streamId, String to, String from, String mimeType, double duration, java.util.Map<String, String> context)
    {
        return _iceI_onAudioEndAsync(streamId, to, from, mimeType, duration, context, false);
    }

    /**
     * @hidden
     * @param iceP_streamId -
     * @param iceP_to -
     * @param iceP_from -
     * @param iceP_mimeType -
     * @param iceP_duration -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onAudioEndAsync(String iceP_streamId, String iceP_to, String iceP_from, String iceP_mimeType, double iceP_duration, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onAudioEnd", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_streamId);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_mimeType);
                     ostr.writeDouble(iceP_duration);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatClientPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatClientPrx.class, _ChatClientPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatClientPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatClientPrx.class, _ChatClientPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatClientPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatClientPrx.class, _ChatClientPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatClientPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatClientPrx.class, _ChatClientPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatClientPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatClientPrx.class, _ChatClientPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatClientPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatClientPrx.class, _ChatClientPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatClientPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatClientPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatClientPrx ice_adapterId(String newAdapterId)
    {
        return (ChatClientPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatClientPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatClientPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatClientPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatClientPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatClientPrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatClientPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatClientPrx ice_connectionCached(boolean newCache)
    {
        return (ChatClientPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatClientPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatClientPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatClientPrx ice_secure(boolean b)
    {
        return (ChatClientPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatClientPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatClientPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatClientPrx ice_preferSecure(boolean b)
    {
        return (ChatClientPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatClientPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatClientPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatClientPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatClientPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatClientPrx ice_collocationOptimized(boolean b)
    {
        return (ChatClientPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatClientPrx ice_twoway()
    {
        return (ChatClientPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatClientPrx ice_oneway()
    {
        return (ChatClientPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatClientPrx ice_batchOneway()
    {
        return (ChatClientPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatClientPrx ice_datagram()
    {
        return (ChatClientPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatClientPrx ice_batchDatagram()
    {
        return (ChatClientPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatClientPrx ice_compress(boolean co)
    {
        return (ChatClientPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatClientPrx ice_timeout(int t)
    {
        return (ChatClientPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatClientPrx ice_connectionId(String connectionId)
    {
        return (ChatClientPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatClientPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatClientPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::chat::ChatClient";
    }
}
