//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default void registerClient(String userId, ChatClientPrx cb)
    {
        registerClient(userId, cb, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerClient(String userId, ChatClientPrx cb, java.util.Map<String, String> context)
    {
        _iceI_registerClientAsync(userId, cb, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(String userId, ChatClientPrx cb)
    {
        return _iceI_registerClientAsync(userId, cb, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(String userId, ChatClientPrx cb, java.util.Map<String, String> context)
    {
        return _iceI_registerClientAsync(userId, cb, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_cb -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerClientAsync(String iceP_userId, ChatClientPrx iceP_cb, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeProxy(iceP_cb);
                 }, null);
        return f;
    }

    default void unregisterClient(String userId)
    {
        unregisterClient(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unregisterClient(String userId, java.util.Map<String, String> context)
    {
        _iceI_unregisterClientAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterClientAsync(String userId)
    {
        return _iceI_unregisterClientAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterClientAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_unregisterClientAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unregisterClientAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unregisterClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, null);
        return f;
    }

    default String createGroup(String name, String[] members)
    {
        return createGroup(name, members, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String createGroup(String name, String[] members, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(name, members, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createGroupAsync(String name, String[] members)
    {
        return _iceI_createGroupAsync(name, members, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createGroupAsync(String name, String[] members, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(name, members, context, false);
    }

    /**
     * @hidden
     * @param iceP_name -
     * @param iceP_members -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_createGroupAsync(String iceP_name, String[] iceP_members, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                     ostr.writeStringSeq(iceP_members);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void sendText(String toType, String to, String fromUser, String text)
    {
        sendText(toType, to, fromUser, text, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendText(String toType, String to, String fromUser, String text, java.util.Map<String, String> context)
    {
        _iceI_sendTextAsync(toType, to, fromUser, text, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendTextAsync(String toType, String to, String fromUser, String text)
    {
        return _iceI_sendTextAsync(toType, to, fromUser, text, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendTextAsync(String toType, String to, String fromUser, String text, java.util.Map<String, String> context)
    {
        return _iceI_sendTextAsync(toType, to, fromUser, text, context, false);
    }

    /**
     * @hidden
     * @param iceP_toType -
     * @param iceP_to -
     * @param iceP_fromUser -
     * @param iceP_text -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendTextAsync(String iceP_toType, String iceP_to, String iceP_fromUser, String iceP_text, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendText", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_toType);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_text);
                 }, null);
        return f;
    }

    default Message[] getHistory(String scope, String id)
    {
        return getHistory(scope, id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Message[] getHistory(String scope, String id, java.util.Map<String, String> context)
    {
        return _iceI_getHistoryAsync(scope, id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Message[]> getHistoryAsync(String scope, String id)
    {
        return _iceI_getHistoryAsync(scope, id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Message[]> getHistoryAsync(String scope, String id, java.util.Map<String, String> context)
    {
        return _iceI_getHistoryAsync(scope, id, context, false);
    }

    /**
     * @hidden
     * @param iceP_scope -
     * @param iceP_id -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Message[]> _iceI_getHistoryAsync(String iceP_scope, String iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Message[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getHistory", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_scope);
                     ostr.writeString(iceP_id);
                 }, istr -> {
                     Message[] ret;
                     ret = MessageSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String beginAudio(String toType, String to, String fromUser, String mimeType)
    {
        return beginAudio(toType, to, fromUser, mimeType, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String beginAudio(String toType, String to, String fromUser, String mimeType, java.util.Map<String, String> context)
    {
        return _iceI_beginAudioAsync(toType, to, fromUser, mimeType, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> beginAudioAsync(String toType, String to, String fromUser, String mimeType)
    {
        return _iceI_beginAudioAsync(toType, to, fromUser, mimeType, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> beginAudioAsync(String toType, String to, String fromUser, String mimeType, java.util.Map<String, String> context)
    {
        return _iceI_beginAudioAsync(toType, to, fromUser, mimeType, context, false);
    }

    /**
     * @hidden
     * @param iceP_toType -
     * @param iceP_to -
     * @param iceP_fromUser -
     * @param iceP_mimeType -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_beginAudioAsync(String iceP_toType, String iceP_to, String iceP_fromUser, String iceP_mimeType, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "beginAudio", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_toType);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_mimeType);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void sendAudioChunk(String streamId, int index, int total, byte[] data)
    {
        sendAudioChunk(streamId, index, total, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendAudioChunk(String streamId, int index, int total, byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioChunkAsync(streamId, index, total, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioChunkAsync(String streamId, int index, int total, byte[] data)
    {
        return _iceI_sendAudioChunkAsync(streamId, index, total, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioChunkAsync(String streamId, int index, int total, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioChunkAsync(streamId, index, total, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_streamId -
     * @param iceP_index -
     * @param iceP_total -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioChunkAsync(String iceP_streamId, int iceP_index, int iceP_total, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudioChunk", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_streamId);
                     ostr.writeInt(iceP_index);
                     ostr.writeInt(iceP_total);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    default void endAudio(String streamId, double duration)
    {
        endAudio(streamId, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void endAudio(String streamId, double duration, java.util.Map<String, String> context)
    {
        _iceI_endAudioAsync(streamId, duration, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> endAudioAsync(String streamId, double duration)
    {
        return _iceI_endAudioAsync(streamId, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> endAudioAsync(String streamId, double duration, java.util.Map<String, String> context)
    {
        return _iceI_endAudioAsync(streamId, duration, context, false);
    }

    /**
     * @hidden
     * @param iceP_streamId -
     * @param iceP_duration -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_endAudioAsync(String iceP_streamId, double iceP_duration, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endAudio", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_streamId);
                     ostr.writeDouble(iceP_duration);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatServicePrx ice_adapterId(String newAdapterId)
    {
        return (ChatServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatServicePrx ice_connectionCached(boolean newCache)
    {
        return (ChatServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_secure(boolean b)
    {
        return (ChatServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_preferSecure(boolean b)
    {
        return (ChatServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatServicePrx ice_collocationOptimized(boolean b)
    {
        return (ChatServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatServicePrx ice_twoway()
    {
        return (ChatServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_oneway()
    {
        return (ChatServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_batchOneway()
    {
        return (ChatServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_datagram()
    {
        return (ChatServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_batchDatagram()
    {
        return (ChatServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatServicePrx ice_compress(boolean co)
    {
        return (ChatServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatServicePrx ice_timeout(int t)
    {
        return (ChatServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatServicePrx ice_connectionId(String connectionId)
    {
        return (ChatServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::chat::ChatService";
    }
}
