//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatClient extends com.zeroc.Ice.Object
{
    void onMessage(Message m, com.zeroc.Ice.Current current);

    void onAudioChunk(String streamId, int index, int total, byte[] data, String mimeType, com.zeroc.Ice.Current current);

    void onAudioEnd(String streamId, String to, String from, String mimeType, double duration, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::chat::ChatClient"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::chat::ChatClient";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onMessage(ChatClient obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Message iceP_m;
        iceP_m = Message.ice_read(istr);
        inS.endReadParams();
        obj.onMessage(iceP_m, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onAudioChunk(ChatClient obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_streamId;
        int iceP_index;
        int iceP_total;
        byte[] iceP_data;
        String iceP_mimeType;
        iceP_streamId = istr.readString();
        iceP_index = istr.readInt();
        iceP_total = istr.readInt();
        iceP_data = istr.readByteSeq();
        iceP_mimeType = istr.readString();
        inS.endReadParams();
        obj.onAudioChunk(iceP_streamId, iceP_index, iceP_total, iceP_data, iceP_mimeType, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_onAudioEnd(ChatClient obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_streamId;
        String iceP_to;
        String iceP_from;
        String iceP_mimeType;
        double iceP_duration;
        iceP_streamId = istr.readString();
        iceP_to = istr.readString();
        iceP_from = istr.readString();
        iceP_mimeType = istr.readString();
        iceP_duration = istr.readDouble();
        inS.endReadParams();
        obj.onAudioEnd(iceP_streamId, iceP_to, iceP_from, iceP_mimeType, iceP_duration, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "onAudioChunk",
        "onAudioEnd",
        "onMessage"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 4:
            {
                return _iceD_onAudioChunk(this, in, current);
            }
            case 5:
            {
                return _iceD_onAudioEnd(this, in, current);
            }
            case 6:
            {
                return _iceD_onMessage(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
