//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public class Message implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String id;

    public String from;

    public String to;

    public String scope;

    public MessageType type;

    public String text;

    public String audioUrl;

    public long createdAt;

    public String mimeType;

    public double duration;

    public Message()
    {
        this.id = "";
        this.from = "";
        this.to = "";
        this.scope = "";
        this.type = MessageType.TEXT;
        this.text = "";
        this.audioUrl = "";
        this.mimeType = "";
    }

    public Message(String id, String from, String to, String scope, MessageType type, String text, String audioUrl, long createdAt, String mimeType, double duration)
    {
        this.id = id;
        this.from = from;
        this.to = to;
        this.scope = scope;
        this.type = type;
        this.text = text;
        this.audioUrl = audioUrl;
        this.createdAt = createdAt;
        this.mimeType = mimeType;
        this.duration = duration;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Message r = null;
        if(rhs instanceof Message)
        {
            r = (Message)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.from != r.from)
            {
                if(this.from == null || r.from == null || !this.from.equals(r.from))
                {
                    return false;
                }
            }
            if(this.to != r.to)
            {
                if(this.to == null || r.to == null || !this.to.equals(r.to))
                {
                    return false;
                }
            }
            if(this.scope != r.scope)
            {
                if(this.scope == null || r.scope == null || !this.scope.equals(r.scope))
                {
                    return false;
                }
            }
            if(this.type != r.type)
            {
                if(this.type == null || r.type == null || !this.type.equals(r.type))
                {
                    return false;
                }
            }
            if(this.text != r.text)
            {
                if(this.text == null || r.text == null || !this.text.equals(r.text))
                {
                    return false;
                }
            }
            if(this.audioUrl != r.audioUrl)
            {
                if(this.audioUrl == null || r.audioUrl == null || !this.audioUrl.equals(r.audioUrl))
                {
                    return false;
                }
            }
            if(this.createdAt != r.createdAt)
            {
                return false;
            }
            if(this.mimeType != r.mimeType)
            {
                if(this.mimeType == null || r.mimeType == null || !this.mimeType.equals(r.mimeType))
                {
                    return false;
                }
            }
            if(this.duration != r.duration)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::chat::Message");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, from);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, to);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, scope);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, type);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, text);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, audioUrl);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, createdAt);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mimeType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, duration);
        return h_;
    }

    public Message clone()
    {
        Message c = null;
        try
        {
            c = (Message)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeString(this.from);
        ostr.writeString(this.to);
        ostr.writeString(this.scope);
        MessageType.ice_write(ostr, this.type);
        ostr.writeString(this.text);
        ostr.writeString(this.audioUrl);
        ostr.writeLong(this.createdAt);
        ostr.writeString(this.mimeType);
        ostr.writeDouble(this.duration);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.from = istr.readString();
        this.to = istr.readString();
        this.scope = istr.readString();
        this.type = MessageType.ice_read(istr);
        this.text = istr.readString();
        this.audioUrl = istr.readString();
        this.createdAt = istr.readLong();
        this.mimeType = istr.readString();
        this.duration = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Message v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Message ice_read(com.zeroc.Ice.InputStream istr)
    {
        Message v = new Message();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Message> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Message v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Message> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Message.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Message _nullMarshalValue = new Message();

    /** @hidden */
    public static final long serialVersionUID = 1284017203L;
}
